### ISSUE TITLE
App Crashing When Opening Swipeable Navigation Fragment

### ISSUE THREAD

**Issue by JkMulti** [massivemadness/Fragula#12]
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at com.ald.devs47.sam.beckman.palettesetups.models.HomeSetupModel.hashCode(Unknown Source:136)
	at androidx.navigation.NavBackStackEntry.hashCode(NavBackStackEntry.kt:256)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.put(HashMap.java:611)
	at androidx.navigation.NavController.linkChildToParent(NavController.kt:143)
	at androidx.navigation.NavController.addEntryToBackStack(NavController.kt:1918)
	at androidx.navigation.NavController.addEntryToBackStack$default(NavController.kt:1813)
	at androidx.navigation.NavController$navigate$4.invoke(NavController.kt:1721)
	at androidx.navigation.NavController$navigate$4.invoke(NavController.kt:1719)
	at androidx.navigation.NavController$NavControllerNavigatorState.push(NavController.kt:287)
	at com.fragula2.navigation.SwipeBackNavigator.navigate(SwipeBackNavigator.kt:54)
	at com.fragula2.navigation.SwipeBackNavigator.navigate(SwipeBackNavigator.kt:33)
	at androidx.navigation.NavController.navigateInternal(NavController.kt:260)
	at androidx.navigation.NavController.navigate(NavController.kt:1719)
	at androidx.navigation.NavController.navigate(NavController.kt:1545)
	at androidx.navigation.NavController.navigate(NavController.kt:1472)
	at androidx.navigation.NavController.navigate(NavController.kt:1454)
	at com.ald.devs47.sam.beckman.palettesetups.recycler.carouselRecycler.CarouselAdapter.onBindViewHolder$lambda$0(CarouselAdapter.kt:136)
	at com.ald.devs47.sam.beckman.palettesetups.recycler.carouselRecycler.CarouselAdapter.lambda$TKKZbMgavm5g5IcEqe_Or5TbKTc(Unknown Source:0)
	at com.ald.devs47.sam.beckman.palettesetups.recycler.carouselRecycler.-$$Lambda$CarouselAdapter$TKKZbMgavm5g5IcEqe_Or5TbKTc.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7743)
	at android.view.View.performClickInternal(View.java:7720)
	at android.view.View.access$3700(View.java:854)
	at android.view.View$PerformClick.run(View.java:29111)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8309)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

**Comment by massivemadness** [comment]
Hi @JkMulti, can you show me your nav graph? What arguments are you passing to a destination?

**Comment by massivemadness** [comment]
Need more details
